name: Firebase Deploy
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build and deploy
        run: |
          npm ci
          npm start
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
         
           - name: Obtener número de PR
            run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

          - name: Generar URL
            run: |
           PR_NUMBER=${{ env.PR_NUMBER }}
           URL="https://miapp.com/pr/${PR_NUMBER}"
           echo "URL=${URL}" >> $GITHUB_ENV

          - name: Display URL
           run: echo "Generated URL:${{ steps.generate_url.outputs.url }}"
          - name: Guardar URL
          run: echo "${URL}" >> url.txt
