name: Firebase Deploy
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build and deploy
        run: |
          npm ci
          npm run build
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
