name: Preview Deployment

on:
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
      - name: Send email notification
        uses: actions/github-script@v4
        env:
          EMAIL_TO: yanfranve@gmail.com
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const emailTo = process.env.EMAIL_TO;
            const subject = "Nuevo enlace de vista previa en Vercel";
            const body = "Se ha creado un nuevo enlace de vista previa:\n\n" +
                         "Enlace: " + process.env.VERCEL_URL;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${emailTo}\n\n${subject}\n\n${body}`
            });

